[package]
name = "wordlevs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.12"
colored = "2.0.0"
clearscreen = "1.0.10"
rpassword = "7.0.0"
